[project]
name = "bapy"
description = "A tool for managing python packages"
dynamic = ["version"]
license = { text = "MIT" }
requires-python = ">=3.10"
[project.scripts]
build = "ppip.cli.project:_build"
ppip = "ppip.cli.__main__:app"

[build-system]
requires = [
    "build >=1.0.3, <2",
    "furl >= 2.1.3, <3",
    "gitpython >= 3.1.36, <4",
    "loguru >=0.7.2, <1",
    "packaging >= 23.1, <24",
    "rich >= 13.5, <14",
    "semver >=3.0.1, <4",
    "setuptools >= 68.2.2, <69",
    "setuptools_scm >= 8.0.3, <9",
    "toml >=0.10.2, <1",
    "twine >= 4.0.2, <5",
    "typer[all] >= 0.9, <1",
    "wheeel >= 0.41.42, <1"
]
build-backend = "ppip.backend"
backend-path = ["."]

[tool.setuptools_scm]
