[project]
dependencies = [
    "nodeps",
]
[project.optional-dependencies]
dev = [
    "pproj[all]",
]

[build-system]
requires = [
    "setuptools >= 68.2.2, <69",
    "setuptools_scm >= 8.0.3, <9",
    "wheel >= 0.41.2, <1"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
